### ISSUE TITLE
Issues restarting rstudio

### ISSUE THREAD

**Issue by johndharrison** [MangoTheCat/processx#23] opened 2016-10-06 22:13 UTC
If I have a processx process running initiated from RStudio and RStudio is restarted there are issues killing processes/child processes. For example in RStudio:

```
library(webdriver)
phantom <- run_phantomjs()
```

Now if we select session -> Restart R

On windows RStudio client we experience a crash. On RStudio server running on Linux a complete freeze is experienced. 

Win 10, R (2016-09-23 r71344) , RStudio  0.99.903
Ubuntu 16.04, R (3.3.1), rstudio-server 0.99.902

**Comment by gaborcsardi** [comment] 2016-10-06 22:13
:(

**Comment by gaborcsardi** [comment] 2016-10-06 22:14
Sorry, did not mean to close..... thanks for reporting.

**Comment by gaborcsardi** [comment] 2016-10-06 22:34
OK, this seems like an RStudio bug to me. If I do

```r
p <- pipe("sleep 100 2>&1", open = "r")
```

and then select Session -> Restart R, then RStudio "freezes". Well, it does not freeze, it just says "Backing up R session" forever. Although it is possible to start a new session or walk around in the menus. If you do "Terminate R", then the session will be eventually aborted.

Maybe we can work around it in `processx` by closing the pipe in the finalizer of the `process` object, I'll try it in a sec.

This is macOS, and RStudio version 0.99.903. Paging @kevinushey

**Comment by gaborcsardi** [comment] 2016-10-06 23:13
Apart from this, there are also problems for the finalizer of `processx` I believe. Whenever I do

```r
p <- process("sleep", "120")
rm(p)
gc()
```

it freezes. `p$kill()` is fine.....

**Comment by gaborcsardi** [comment] 2016-10-06 23:17
Hmmm, even without the finalizer it freezes:

```r
library(processx)
p <- process$new("sleep", "120", cleanup = FALSE)
rm(p)
gc()
```

So maybe it is the pipe, after all.

**Comment by gaborcsardi** [comment] 2016-10-06 23:18
Or the finalizer of `process_connection`.....

**Comment by gaborcsardi** [comment] 2016-10-06 23:20
Yeah, it is the finalizer of `process_connection` if `cleanup = FALSE`. In this case the `close` on the pipe waits for the sleep process to finish, at least on OSX.

**Comment by gaborcsardi** [comment] 2016-10-06 23:29
OK, I got it. In the pipe-only case, RStudio calls `close()` on the pipe, but that never returns, or only 2 minutes later in case of the sleep.

In case of `processx`, we also have a finalizer on the pipe, and that is called first, and the same happens. So the workaround is to make sure that we kill the child process first. We cannot choose the order of the finalizers, so we'll have to close the pipe from the finalizer of the process object. 

It is possibly that we cannot avoid an "unused connection closed" warning in this case, but that's way better than a freeze.....

**Comment by gaborcsardi** [comment] 2016-10-06 23:44
OK, we can now at least call `rm(x); gc()` on `processx` objects, in RStudio as well.

Restarting R in Rstudio still fails, probably because RStudio tries to close the pipe connection first, but that never finishes. So I still think that this is an RStudio bug: if there is a pipe connection, it should not try to close that, at least not before the finalizers run and/or all child processes of the R session are killed.

**Comment by gaborcsardi** [comment] 2016-10-07 08:00
So, assuming RStudio will not handle `pipe()`, it is possible to rewrite processx without pipes, that was my first implementation, actually. 

AFAIR the only messy operation is waiting on the process. This is easy with a pipe, you just read from it (with a blocking read), until there is no data (just close() does not work on windows). Not so easy if we just start the process with system2(). But it is also not impossible I think.

It is probably a significant amount of work, about a full day, to make sure that things work on all platforms.

**Comment by johndharrison** [comment] 2016-10-07 11:32
`tools.rstudio` has a .`rs.restartR` function with an `afterRestartCommand` maybe there is a hook
that can be called if we know we are operating within rstudio

```
> .rs.restartR
function (afterRestartCommand = "") 
{
    afterRestartCommand <- paste(as.character(afterRestartCommand), 
        collapse = "\n")
    .Call(.rs.routines$rs_restartR, afterRestartCommand)
}
```

**Comment by gaborcsardi** [comment] 2016-10-07 11:58
@johndharrison Thanks, I'll take a look.

**Comment by gaborcsardi** [comment] 2016-10-07 12:17
@johndharrison Looks like that function is not called when doing a restart from the menu. And I could not find any hook in `tools:rstudio`. Maybe I just missed it, there are a lot of things there.....

**Comment by gaborcsardi** [comment] 2016-10-07 12:26
Wait, maybe there is an easy solution. The connection is an S3 object, so I can just override the close method to kill the process first. This could work.

**Comment by gaborcsardi** [comment] 2016-10-07 12:48
It does not work, unfortunately, the S3 close method is not called at all.....

**Comment by kevinushey** [comment] 2016-10-07 21:17
I don't have any answers either, unfortunately :/

**Comment by wch** [comment] 2016-10-27 18:50
I encounter this problem even with RStudio, when saving the workspace is enabled. For example, running this from a terminal will cause it to hang. 

```R
R --save
p <- pipe("sleep 100 2>&1", open = "r")
q()
```

At this point, pressing ctrl-C will cause it exit. It also appears to kill the `sleep` process. This is on Ubuntu 16.04.

**Comment by gaborcsardi** [comment] 2016-10-27 21:03
> I encounter this problem even with RStudio,

Wait, you mean **without** RStudio, right?

OK, this kind of makes sense, actually, if I think about it. It is waiting for the child process to finish. (*Kind of* makes sense......)

But the sad thing is, finalizers are not called until R starts waiting on the child process, so we have no chance to kill the pipe.

**Comment by wch** [comment] 2016-10-27 21:08
Oh yes, without. Sorry!

**Comment by wch** [comment] 2016-10-27 21:14
So it waits for the child process to finish only when saving the workspace? That doesn't really make sense to me. Can you explain that a bit?


FWIW, manually saving the object works fine. This works without any problems:

```R
R
library(devtools);library(testthat)
load_all()
app <- shinyapp$new(test_path("apps/test-exports/"))
save(app, file ="test.RData")
save.image(file ="test.RData")
q()
```

**Comment by gaborcsardi** [comment] 2016-10-27 21:16
@wch Sorry, I missed the `--save` bit. Right, I agree, does not make any sense... probably not inteded behavior, just some side effect....

**Comment by wch** [comment] 2016-10-28 21:15
Here's a minimal example of the two cases:

```
R
p <- pipe("sleep 100 2>&1", open = "r")
# Quitting with saving workspace results in a hang
q(save="yes")
```


```
R
p <- pipe("sleep 100 2>&1", open = "r")
# Manually saving workspace and then quitting does not hang
save.image()
q(save="no")
```

Digging into R sources:

* When you quit and save workspace, it calls [`Rstd_CleanUp`](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/unix/sys-std.c#L1127).
* That calls `R_SaveGlobalEnv`, which calls [`R_SaveGlobalEnvToFile`](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/main/saveload.c), which calls the R function `sys.save.image`.
* `sys.save.image` calls `closeConnections()`, right before `save.image()`.


So I found that `closeAllConnections()` actually causes the hang:

```
R
p <- pipe("sleep 100 2>&1", open = "r");
# Hangs
closeAllConnections()
```


And closing the single connection hangs:

```
R
p <- pipe("sleep 100 2>&1", open = "r");
# Hangs
close.connection(p)
```

**Comment by gaborcsardi** [comment] 2016-10-29 20:38
@wch Thanks for the investigation! 

Unfortunately connections are somewhat messed up in R. It is not a problem that it is closing the connection, the problem is that if a connection is an S3 object, then it should call the generic `close` method, and then I could kill the process....

Anyway, I don't see any way out with the `pipe`, but we need to go back to `system`. Or rewrite in C/C++. :(

**Comment by gaborcsardi** [comment] 2016-11-17 23:50
I rewrote the process start and some other bits, so `processx` does not use `pipe()` any more, it only uses plain old `system`. It is in the `nopipe` branch. So far only tested on macOS, but all test cases pass, and this RStudio "Restart R" bug does not come up, either: the R session is restarted, and the phantom process is killed.

There are some compromises, I need to sleep-wait when starting the process, and also when waiting on it. I think these are OK.

I will test windows tomorrow, it is broken, but probably fixable....

**Closed** 2016-11-18 13:51 UTC

**Comment by gaborcsardi** [comment] 2016-11-18 13:53
@johndharrison @wch Please test when you have time, and let me know if you still have problems. Thanks much!
